### ISSUE TITLE
always_populate_raw_post_data PHP setting: Not set to -1

### ISSUE THREAD

**Issue by andypost** [RobLoach/drush-docker#12]
This caused wrong default php setting shipped
This is a requirement for core's rest module 
"datails":https://api.drupal.org/api/drupal/core!modules!rest!rest.install/function/rest_requirements/8

**Comment by RobLoach** [comment]
Perhaps it's time to update to PHP 7: https://github.com/RobLoach/docker-composer/pull/30

**Comment by andypost** [comment]
) idea is fine but 5.6 still used
