### ISSUE TITLE
Backdrop Drush Plugins

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/drush-docker#14]
https://github.com/backdrop-contrib/drush

**Comment by pirog** [comment]
see #15 if you are interested in giving up all the glory 

:100: x :100: / :100: = :100:

**Comment by RobLoach** [comment]
Should be up by now!

**Comment by pirog** [comment]
I went into the docker hub to add the tag but you beat me to it! Thanks as
always and may you always live your life like William T. Riker and not his
"compromised second draft" "brother" Thomas

**Comment by RobLoach** [comment]
`backdrop-user-login` is in the command list! It works :+1:

**Comment by pirog** [comment]
yay!
