### ISSUE TITLE
Container lacks MySQL client and PDO extension

### ISSUE THREAD

**Issue by socketwench** [RobLoach/drush-docker#4]
Currently you cannot execute cr all or sql-client on on the container. Instead, you get the following error:

```
Fatal error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 119
Drush command terminated abnormally due to an unrecoverable error.                                                                                                         [error]
Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php, line 119
```

**Comment by socketwench** [comment]
Apparently the solution is to add the following line to the Dockerfile:

```
RUN docker-php-ext-install mysql mysqli pdo pdo_mysql
```

**Comment by andytruong** [comment]
Duplicate to https://github.com/RobLoach/drush-docker/pull/3, not sure why @RobLoach  doesn't merge it.

**Comment by RobLoach** [comment]
Thanks for the ping, @andytruong .

**Comment by mparker17** [comment]
#3 is merged; I think this is done now? I can certainly run `drush sql*` commands now. But I don't have permission to close this issue.

**Comment by RobLoach** [comment]
@mparker17 I couldn't get Drush 6 to run, in any context. Also removed the minor versions, just left the major specificity. Think we need them?

**Comment by RobLoach** [comment]
Worked!
